services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wannabePROD_local
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - USER=fotis
      - PASS=vach