services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wannabeUAT_local
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
      - USER=fotis
      - PASS=vach